// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRl-TXFH_pkwGm3EIHgqdqSD16BbMQvug',
    appId: '1:927206952114:web:d2c684a42d3e37a1d88dab',
    messagingSenderId: '927206952114',
    projectId: 'heartlink-dating-project',
    authDomain: 'heartlink-dating-project.firebaseapp.com',
    databaseURL: 'https://heartlink-dating-project-default-rtdb.firebaseio.com',
    storageBucket: 'heartlink-dating-project.appspot.com',
    measurementId: 'G-Y8KBPQ1WPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhds0TxN-XUh1k5MAMbVeUbc5zV71y6no',
    appId: '1:927206952114:android:433ae0a2e2f9c495d88dab',
    messagingSenderId: '927206952114',
    projectId: 'heartlink-dating-project',
    databaseURL: 'https://heartlink-dating-project-default-rtdb.firebaseio.com',
    storageBucket: 'heartlink-dating-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyOFoduumROHE0FLuZ-e0rrHrYd8Gmx9Q',
    appId: '1:927206952114:ios:f8e1eadae4539cf9d88dab',
    messagingSenderId: '927206952114',
    projectId: 'heartlink-dating-project',
    databaseURL: 'https://heartlink-dating-project-default-rtdb.firebaseio.com',
    storageBucket: 'heartlink-dating-project.appspot.com',
    androidClientId: '927206952114-73lagmaoh9j4lqpi8pjrep5evsshjssk.apps.googleusercontent.com',
    iosClientId: '927206952114-dgpa3hr5odfqqcoitq0j4c9phq3n6g8i.apps.googleusercontent.com',
    iosBundleId: 'com.amobi.barcode.qrcode.scanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyOFoduumROHE0FLuZ-e0rrHrYd8Gmx9Q',
    appId: '1:927206952114:ios:b4df638b39be1eeed88dab',
    messagingSenderId: '927206952114',
    projectId: 'heartlink-dating-project',
    databaseURL: 'https://heartlink-dating-project-default-rtdb.firebaseio.com',
    storageBucket: 'heartlink-dating-project.appspot.com',
    androidClientId: '927206952114-73lagmaoh9j4lqpi8pjrep5evsshjssk.apps.googleusercontent.com',
    iosClientId: '927206952114-li4504qt6qpdmj24jhhdpge0t8lhom7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingApp',
  );
}
